INSTAGRAM = "https://instagram.com/"
TWITTER = "https://x.com/"
FACEBOOK = "https://facebook.com/"
TO1337X = "https://www.1337x.to/user/"
EIGHT_TRACKS = "https://8tracks.com/"
NINE_GAG = "https://www.9gag.com/u/"
ABOUT_ME = "https://about.me/"
ACADEMIA = "https://independent.academia.edu/"
AIRLINERS = "https://www.airliners.net/user/profile/photos"
ALL_MY_LINKS = "https://allmylinks.com/"
ANIWORLD = "https://aniworld.to/user/profil/"
ANILIST = "https://anilist.co/user/"
APPLE_DEV = "https://developer.apple.com/forums/profile/"
APPLE_DISCUSSIONS = "https://discussions.apple.com/profile/"
ARCHIVE_OF_OUR_OWN = "https://archiveofourown.org/users/"
ATCODER = "https://atcoder.jp/users/"
AUDIOJUNGLE = "https://audiojungle.net/user/"
BOOTH = "https://booth.pm/"
BANDCAMP = "https://www.bandcamp.com/"
BEHANCE = "https://www.behance.net/"
BEZUYTECZNA = "https://bezuzyteczna.pl/uzytkownicy/"
BOARDGAMEGEEK = "https://boardgamegeek.com/user/"
BOOKCROSSING = "https://www.bookcrossing.com/mybookshelf/"
BUY_ME_A_COFFEE = "https://buymeacoff.ee/"
BUZZFEED = "https://buzzfeed.com/"
CGTRADER = "https://www.cgtrader.com/"
CARBONMADE = "https://carbonmade.com"
CHAMPIONAT = "https://www.championat.com/user/"
CHATUJME_CZ = "https://profil.chatujme.cz/"
CHESS = "https://www.chess.com/member/"
CLAPPER = "https://clapperapp.com/"
CLOZEMASTER = "https://www.clozemaster.com/players/"
CLUBHOUSE = "https://www.clubhouse.com/@"
CODEBERG = "https://codeberg.org/"
CODECADEMY = "https://www.codecademy.com/profiles/"
CODECHEF = "https://www.codechef.com/users/"
CODEFORCES = "https://codeforces.com/profile/"
CODEWARS = "https://www.codewars.com/users/"
COLOURLOVERS = "https://www.colourlovers.com/lover/"
COROFLOT = "https://www.coroflot.com/"
CROWDIN = "https://crowdin.com/profile/"
CULTS3D = "https://cults3d.com/en/users/creations"
DEV_COMMUNITY = "https://dev.to/"
DMOJ = "https://dmoj.ca/user/"
DAILYMOTION = "https://www.dailymotion.com/"
DEALABS = "https://www.dealabs.com/profile/"
DISCORD = "https://discord.com"
DISCUS_ELASTIC = "https://discuss.elastic.co/u/"
DISQUS = "https://disqus.com/"
DRIBBBLE = "https://dribbble.com/"
DUOLINGO = "https://www.duolingo.com/profile/"
EINTRACHT_FRANKFURT = "https://community.eintracht.de/fans/"
EMPRETIENDA_AR = "https://empretienda.com.ar"
EXPOSURE = "https://exposure.co/"
EXOPHASE = "https://www.exophase.com/user/"
EYEEM = "https://www.eyeem.com/u/"
F3_COOL = "https://f3.cool/"
FANPOP = "https://www.fanpop.com/fans/"
FLICKR = "https://www.flickr.com/people/"
FLIGHTRADAR24 = "https://my.flightradar24.com/"
FLIPBOARD = "https://flipboard.com/@"
FREELANCE_HABR = "https://freelance.habr.com/freelancers/"
FREELANCER = "https://www.freelancer.com/u/"
GAIAONLINE = "https://www.gaiaonline.com/profiles/"
GAMESPOT = "https://www.gamespot.com/profile/"
GIPHY = "https://giphy.com/"
GITHUB = "https://www.github.com/"
GITEE = "https://gitee.com/"
GOODREADS = "https://www.goodreads.com/"
GRAILED = "https://www.grailed.com/"
GUMROAD = "https://www.gumroad.com/"
HACKADAY = "https://hackaday.io/"
HACKENPROOF = "https://hackenproof.com/hackers/"
HACKEREARTH = "https://hackerearth.com/@"
HACKERNEWS = "https://news.ycombinator.com/user?id="
HACKERONE = "https://hackerone.com/"
HASHNODE = "https://hashnode.com/@"
HOUZZ = "https://houzz.com/user/"
HUDSONROCK = "https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-username?username="
IFTTT = "https://www.ifttt.com/p/"
IMGUR = "https://imgur.com/user/"
INSTRUCTABLES = "https://www.instructables.com/member/"
ISSUU = "https://issuu.com/"
ITCH_IO = "https://itch.io"
KASKUS = "https://www.kaskus.co.id/@"
KONGREGATE = "https://www.kongregate.com/accounts/"
LOR = "https://www.linux.org.ru/people/profile"
LAUNCHPAD = "https://launchpad.net/~"
LETTERBOXD = "https://letterboxd.com/"
LIBRARYTHING = "https://www.librarything.com/profile/"
LICHESS = "https://lichess.org/@/"
LINKEDIN = "https://linkedin.com/in/"
LINKTREE = "https://linktr.ee/"
LIVEJOURNAL = "https://livejournal.com"
MMORPG_FORUM = "https://forums.mmorpg.com/profile/"
MEDIUM = "https://medium.com/@"
MEMRISE = "https://www.memrise.com/user/"
MIXCLOUD = "https://www.mixcloud.com/"
MONKEYTYPE = "https://monkeytype.com/profile/"
MYANIMELIST = "https://myanimelist.net/profile/"
MYMINIFACTORY = "https://www.myminifactory.com/users/"
MYDRAMALIST = "https://www.mydramalist.com/profile/"
MYSPACE = "https://myspace.com/"
NATIONSTATES_NATION = "https://nationstates.net/nation="
NAVER = "https://blog.naver.com/"
NEEDROM = "https://www.needrom.com/author/"
NEWGROUNDS = "https://newgrounds.com"
NITROTYPE = "https://www.nitrotype.com/racer/"
NOTABUG_ORG = "https://notabug.org/"
NYAA_SI = "https://nyaa.si/user/"
PACKAGIST = "https://packagist.org/packages/"
PASTEBIN = "https://pastebin.com/u/"
PERISCOPE = "https://www.periscope.tv/"
POLARSTEPS = "https://polarsteps.com/"
PRODUCTHUNT = "https://www.producthunt.com/@"
PROMODJ = "http://promodj.com/"
PYPI = "https://pypi.org/user/"
RAJCE_NET = "https://rajce.idnes.cz/"
RARIBLE = "https://rarible.com/marketplace/api/v4/urls/"
REDDIT = "https://www.reddit.com/user/"
REPLIT = "https://replit.com/@"
REVERBNATION = "https://www.reverbnation.com/"
RUNESCAPE = "https://apps.runescape.com/runemetrics/app/overview/player/"
SBBAZAR_CZ = "https://sbazar.cz/"
SCRIBD = "https://scribd.com"
SHPOCK = "https://shpock.com"
SKETCHFAB = "https://sketchfab.com"
SLACK = "https://slack.com"
SLASHDOT = "https://slashdot.org/~"
SLIDESHARE = "https://slideshare.net"
SLIDES = "https://slides.com"
SMUGMUG = "https://smugmug.com"
SMULE = "https://smule.com"
SOUNDCLOUD = "https://soundcloud.com"
SPEEDRUN = "https://speedrun.com/users/"
SPELLS8 = "https://forum.spells8.com/u/"
SPORCLE = "https://www.sporcle.com/user//people"
SPOTIFY = "https://open.spotify.com/user/"
STAR_CITIZEN = "https://robertsspaceindustries.com/citizens/"
STEAM_COMMUNITY_USER = "https://steamcommunity.com/id//"
STRAVA = "https://www.strava.com/athletes/"
TETR_IO = "https://ch.tetr.io/u/"
TIENDANUBE = "https://.mitiendanube.com/"
TLDR_LEGAL = "https://tldrlegal.com/users//"
TOPCODER = "https://profiles.topcoder.com//"
TENOR = "https://tenor.com/users/"
THEMEFOREST = "https://themeforest.net/user/"
TRADINGVIEW = "https://www.tradingview.com/u//"
TRASHBOXRU = "https://trashbox.ru/users/"
TRELLO = "https://trello.com/"
TRYHACKME = "https://tryhackme.com/p/"
TUNA = "https://tuna.voicemod.net/user/"
TWITCH = "https://www.twitch.tv/"
TWITTER = "https://x.com/"
TYPERACER = "https://data.typeracer.com/pit/profile?user="
ULTIMATE_GUITAR = "https://ultimate-guitar.com/u/"
UNSPLASH = "https://unsplash.com/@"
UNTAPPD = "https://untappd.com/user/"
VSCO = "https://vsco.co/"
VELOMANIA = "https://forum.velomania.ru/member.php?username="
VERO = "https://vero.co/"
VIMEO = "https://vimeo.com/"
VIRUSTOTAL = "https://www.virustotal.com/gui/user/"
VLR = "https://www.vlr.gg/user/"
WARRIOR_FORUM = "https://www.warriorforum.com/members/.html"
WEEBLY = "https://.weebly.com/"
WIKIDOT = "http://www.wikidot.com/user:info/"
WIKIPEDIA = "https://en.wikipedia.org/wiki/Special:CentralAuth/?uselang=qqx"
WORDPRESS = "https://.wordpress.com/"
WORDPRESSORG = "https://profiles.wordpress.org//"
WORDNIK = "https://www.wordnik.com/users/"
WYKOP = "https://www.wykop.pl/ludzie/"
XBOX_GAMERTAG = "https://xboxgamertag.com/search/"
YOUNOW = "https://www.younow.com/"
YOUTUBE = "https://www.youtube.com/@"
AKNIGA = "https://akniga.org/profile/"
BABYBLOGRU = "https://www.babyblog.ru/user/"
COUCHSURFING = "https://www.couchsurfing.com/people/"
D3RU = "https://d3.ru/user//posts"
DAILYKOS = "https://www.dailykos.com/user/"
DATINGRU = "http://dating.ru/"
DRIVE2 = "https://www.drive2.ru/users/"
EINTRACHT = "https://community.eintracht.de/fans/"
FIXYA = "https://www.fixya.com/users/"
FL = "https://www.fl.ru/users/"
FORUM_GUNS = "https://forum.guns.ru/forummisc/blog/"
FREECODECAMP = "https://www.freecodecamp.org/"
FURAFFINITY = "https://www.furaffinity.net/user/"
GEOCACHING = "https://www.geocaching.com/p/default.aspx?u="
HABR = "https://habr.com/ru/users/"
HACKSTER = "https://www.hackster.io/"
HUNTING = "https://www.hunting.ru/forum/members/?username="
IMGSRC_RU = "https://imgsrc.ru/main/user.php?user="
IGROMANIA = "http://forum.igromania.ru/member.php?username="
INTERPALS = "https://www.interpals.net/"
JBZD_COM_PL = "https://jbzd.com.pl/uzytkownik/"
JEUXVIDEO = "https://www.jeuxvideo.com/profil/"
KOFI = "https://ko-fi.com/"
KWORK = "https://kwork.ru/user/"
LASTFM = "https://last.fm/user/"
LIVELIB = "https://www.livelib.ru/reader/"
MASTODON_CLOUD = "https://mastodon.cloud/@"
MASTODON_SOCIAL = "https://mastodon.social/@"
MERCADOLIVRE = "https://www.mercadolivre.com.br/perfil/"
MINDS = "https://www.minds.com//"
NNRU = "https://.www.nn.ru/"
NPM = "https://www.npmjs.com/~"
OSU = "https://osu.ppy.sh/users/"
PIKABU = "https://pikabu.ru/@"
PR0GRAMM = "https://pr0gramm.com/user/"
SATISRU = "https://satsis.info/user/"
THREADS = "https://www.threads.net/@"




SITES = [
    INSTAGRAM, TWITTER, FACEBOOK, TO1337X, EIGHT_TRACKS, NINE_GAG, ABOUT_ME, ACADEMIA, AIRLINERS, ALL_MY_LINKS, 
    ANIWORLD, ANILIST, APPLE_DEV, APPLE_DISCUSSIONS, ARCHIVE_OF_OUR_OWN, ATCODER, AUDIOJUNGLE, BOOTH, BANDCAMP, 
    BEHANCE, BEZUYTECZNA, BOARDGAMEGEEK, BOOKCROSSING, BUY_ME_A_COFFEE, BUZZFEED, CGTRADER, CARBONMADE, CHAMPIONAT, 
    CHATUJME_CZ, CHESS, CLAPPER, CLOZEMASTER, CLUBHOUSE, CODEBERG, CODECADEMY, CODECHEF, CODEFORCES, CODEWARS, 
    COLOURLOVERS, COROFLOT, CROWDIN, CULTS3D, DEV_COMMUNITY, DMOJ, DAILYMOTION, DEALABS, DISCORD, DISCUS_ELASTIC, 
    DISQUS, DRIBBBLE, DUOLINGO, EINTRACHT_FRANKFURT, EMPRETIENDA_AR, EXPOSURE, EXOPHASE, EYEEM, F3_COOL, FANPOP, 
    FLICKR, FLIGHTRADAR24, FLIPBOARD, FREELANCE_HABR, FREELANCER, GAIAONLINE, GAMESPOT, GIPHY, GITHUB, GITEE, 
    GOODREADS, GRAILED, GUMROAD, HACKADAY, HACKENPROOF, HACKEREARTH, HACKERNEWS, HACKERONE, HASHNODE, HOUZZ, 
    HUDSONROCK, IFTTT, IMGUR, INSTRUCTABLES, ISSUU, ITCH_IO, KASKUS, KONGREGATE, LOR, LAUNCHPAD, LETTERBOXD, 
    LIBRARYTHING, LICHESS, LINKEDIN, LINKTREE, LIVEJOURNAL, MMORPG_FORUM, MEDIUM, MEMRISE, MIXCLOUD, MONKEYTYPE, 
    MYANIMELIST, MYMINIFACTORY, MYDRAMALIST, MYSPACE, NATIONSTATES_NATION, NAVER, NEEDROM, NEWGROUNDS, NITROTYPE, 
    NOTABUG_ORG, NYAA_SI, PACKAGIST, PASTEBIN, PERISCOPE, POLARSTEPS, PRODUCTHUNT, PROMODJ, PYPI, RAJCE_NET, RARIBLE, 
    REDDIT, REPLIT, REVERBNATION, RUNESCAPE, SBBAZAR_CZ, SCRIBD, SHPOCK, SKETCHFAB, SLACK, SLASHDOT, SLIDESHARE, 
    SLIDES, SMUGMUG, SMULE, SOUNDCLOUD, SPEEDRUN, SPELLS8, SPORCLE, SPOTIFY, STAR_CITIZEN, STEAM_COMMUNITY_USER, 
    STRAVA, TETR_IO, TIENDANUBE, TLDR_LEGAL, TOPCODER, TENOR, THEMEFOREST, TRADINGVIEW, TRASHBOXRU, TRELLO, TRYHACKME, 
    TUNA, TWITCH, TWITTER, TYPERACER, ULTIMATE_GUITAR, UNSPLASH, UNTAPPD, VSCO, VELOMANIA, VERO, VIMEO, VIRUSTOTAL, 
    VLR, WARRIOR_FORUM, WEEBLY, WIKIDOT, WIKIPEDIA, WORDPRESS, WORDPRESSORG, WORDNIK, WYKOP, XBOX_GAMERTAG, YOUNOW, 
    YOUTUBE, AKNIGA, BABYBLOGRU, COUCHSURFING, D3RU, DAILYKOS, DATINGRU, DRIVE2, EINTRACHT, FIXYA, FL, FORUM_GUNS, 
    FREECODECAMP, FURAFFINITY, GEOCACHING, HABR, HACKSTER, HUNTING, IMGSRC_RU, IGROMANIA, INTERPALS, JBZD_COM_PL, 
    JEUXVIDEO, KOFI, KWORK, LASTFM, LIVELIB, MASTODON_CLOUD, MASTODON_SOCIAL, MERCADOLIVRE, MINDS, NNRU, NPM, OSU, 
    PIKABU, PR0GRAMM, SATISRU, THREADS,
]
